config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard', to: 'dashboard#index', as: 'admin_dashboard'
  get 'admin/dashboard/books', to: 'dashboard#books'
  get 'admin/dashboard/genres', to: 'dashboard#genres'
  get 'admin/dashboard/users', to: 'dashboard#users'
  get 'admin/dashboard/orders', to: 'dashboard#orders'
  get 'home/index'

  resources :books, except: [:index]
  resources :genres, except: [:index]

  resources :genres do
    member do
      get 'delete', to: 'genres#delete'
    end
  end

  resources :books do
    member do
      get 'delete', to: 'books#delete'
    end
  end

  resources :carts, only: [] do
    post 'add', on: :collection
    delete 'remove', on: :collection
    post 'update_quantity', on: :collection
    post 'stripe_checkout', on: :collection
  end

  resources :orders, only: [] do
    collection do
      get 'success', to: 'orders#success', as: 'success'
      get 'cancel', to: 'orders#cancel', as: 'cancel'
    end
  end

  get 'checkout', to: 'carts#checkout', as: 'checkout'


  devise_for :admins, path: 'admin', skip: [:registrations, :passwords]

  devise_for :users, path: '', skip: [:passwords]

  root "home#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def books
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true).includes(:genre.name).paginate(page: params[:page], per_page: 10)
  end

  def genres
    @q = Genre.ransack(params[:q])
    @genres = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
  end

  def users
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).paginate(page: params[:page], per_page: 10)
  end

  def orders
    @q = Order.ransack(params[:q])
    @orders = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/books.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="p-5 h-screen w-full bg-gray-100">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-xl mb-2">Books</h1>
      <%= link_to "Add Book", new_book_path, data: { turbo_frame: 'modal' }, class: "bg-primary-700 text-white rounded-lg px-5 py-2.5" %>
    </div>
    <div class="mb-6">
      <%= search_form_for @q, url: admin_dashboard_books_path, method: :get, html: { class: 'flex items-center' } do |f| %>
        <div class="relative w-full">
          <%= f.search_field :title_or_author_cont, placeholder: "Search Books", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full pl-10 p-2.5" %>
        </div>
        <%= f.submit 'Search', class: "bg-primary-700 text-white rounded-lg px-5 py-2.5 ml-2" %>
      <% end %>
    </div>
    <div class="overflow-auto rounded-lg shadow hidden md:block mb-6">
      <table class="w-full">
        <thead class="bg-gray-50 border-b-2 border-gray-200">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :title, 'Title') %>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :author, 'Author') %>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :genre, 'Genre') %>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :price, 'Price') %>
          </th>
          <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Actions</th>
        </tr>
        </thead>
        <tbody id="books" class="divide-y divide-gray-100">
        <% @books.each do |book| %>
          <tr id="<%= dom_id(book) %>" class="bg-white">
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <p class="text-gray-700 font-bold"><%= book.title %></p>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= book.author %>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= book.genre.name %>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= number_to_currency(book.price) %>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= link_to "Delete", delete_book_path(book), data: { turbo_frame: 'modal' }, class: "text-red-600 hover:underline" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="flex justify-center mt-4">
      <div class="max-w-xs">
        <%= paginate @books, outer_window: 3 %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/genres.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="p-5 h-screen w-full bg-gray-100">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-xl mb-2">Genres</h1>
      <%= link_to "Add Genre", new_genre_path, data: { turbo_frame: 'modal' }, class: "bg-primary-700 text-white rounded-lg px-5 py-2.5" %>
    </div>
    <div class="mb-6">
      <%= search_form_for @q, url: admin_dashboard_genres_path, method: :get, html: { class: 'flex items-center' } do |f| %>
        <div class="relative w-full">
          <%= f.search_field :name_cont, placeholder: "Search Genres", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full pl-10 p-2.5" %>
        </div>
        <%= f.submit 'Search', class: "bg-primary-700 text-white rounded-lg px-5 py-2.5 ml-2" %>
      <% end %>
    </div>
    <div class="overflow-auto rounded-lg shadow hidden md:block mb-6">
      <table class="w-full">
        <thead class="bg-gray-50 border-b-2 border-gray-200">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :name, 'Genre Name') %>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Description
          </th>
          <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Actions</th>
        </tr>
        </thead>
        <tbody id="genres" class="divide-y divide-gray-100">
        <% @genres.each do |genre| %>
          <tr id="<%= dom_id(genre) %>" class="bg-white">
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <p class="text-gray-700 font-bold"><%= genre.name %></p>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= genre.description %>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= link_to "Delete", delete_genre_path(genre), data: { turbo_frame: 'modal' }, class: "text-red-600 hover:underline" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="flex justify-center mt-4">
      <div class="max-w-xs">
        <%= paginate @genres, outer_window: 3 %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<div class="flex w-full">
  <%= render 'shared/sidebar' %>
  <div class="flex w-full">
    <%= turbo_frame_tag "content", src: admin_dashboard_books_path, class: "w-full" %>
  </div>
</div>

app/views/dashboard/orders.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="p-5 h-screen w-full bg-gray-100">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-xl mb-2">Orders</h1>
    </div>
    <div class="mb-6">
      <%= search_form_for @q, url: admin_dashboard_orders_path, method: :get, html: { class: 'flex items-center' } do |f| %>
        <div class="relative w-full">
          <%= f.search_field :user_email_cont, placeholder: "Search by User Email", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full pl-10 p-2.5" %>
        </div>
        <%= f.submit 'Search', class: "bg-primary-700 text-white rounded-lg px-5 py-2.5 ml-2" %>
      <% end %>
    </div>
    <div class="overflow-auto rounded-lg shadow hidden md:block mb-6">
      <table class="w-full">
        <thead class="bg-gray-50 border-b-2 border-gray-200">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :user_id, 'User') %>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :total_amount, 'Total Amount') %>
          </th>
        </tr>
        </thead>
        <tbody id="orders" class="divide-y divide-gray-100">
        <% @orders.each do |order| %>
          <tr id="<%= dom_id(order) %>" class="bg-white">
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <p class="text-gray-700 font-bold"><%= User.find(order.user_id).email %></p>
            </td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <%= number_to_currency(order.total_amount) %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="flex justify-center mt-4">
      <div class="max-w-xs">
        <%= paginate @orders, outer_window: 3 %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/users.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="p-5 h-screen w-full bg-gray-100">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-xl mb-2">Users</h1>
    </div>
    <div class="mb-6">
      <%= search_form_for @q, url: admin_dashboard_users_path, method: :get, html: { class: 'flex items-center' } do |f| %>
        <div class="relative w-full">
          <%= f.search_field :email_cont, placeholder: "Search Users by Email", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full pl-10 p-2.5" %>
        </div>
        <%= f.submit 'Search', class: "bg-primary-700 text-white rounded-lg px-5 py-2.5 ml-2" %>
      <% end %>
    </div>
    <div class="overflow-auto rounded-lg shadow hidden md:block mb-6">
      <table class="w-full">
        <thead class="bg-gray-50 border-b-2 border-gray-200">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <%= sort_link(@q, :email, 'Email') %>
          </th>
        </tr>
        </thead>
        <tbody id="users" class="divide-y divide-gray-100">
        <% @users.each do |user| %>
          <tr id="<%= dom_id(user) %>" class="bg-white">
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
              <p class="text-gray-700 font-bold"><%= user.email %></p>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="flex justify-center mt-4">
      <div class="max-w-xs">
        <%= paginate @users, outer_window: 3 %>
      </div>
    </div>
  </div>
<% end %>