config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard', to: 'dashboard#index', as: 'admin_dashboard'
  get 'admin/dashboard/books', to: 'dashboard#books'
  get 'admin/dashboard/genres', to: 'dashboard#genres'
  get 'admin/dashboard/users', to: 'dashboard#users'
  get 'admin/dashboard/orders', to: 'dashboard#orders'
  get 'home/index'

  resources :books, except: [:index]
  resources :genres, except: [:index]

  resources :genres do
    member do
      get 'delete', to: 'genres#delete'
    end
  end

  resources :books do
    member do
      get 'delete', to: 'books#delete'
    end
  end

  resources :carts, only: [] do
    post 'add', on: :collection
    delete 'remove', on: :collection
    post 'update_quantity', on: :collection
    post 'stripe_checkout', on: :collection
  end

  resources :orders, only: [] do
    collection do
      get 'success', to: 'orders#success', as: 'success'
      get 'cancel', to: 'orders#cancel', as: 'cancel'
    end
  end

  get 'checkout', to: 'carts#checkout', as: 'checkout'


  devise_for :admins, path: 'admin', skip: [:registrations, :passwords]

  devise_for :users, path: '', skip: [:passwords]

  root "home#index"
end

app/views/shared/_cart_dropdown.html.erb
<div id="cart_dropdown" class="hidden absolute top-full right-0 z-50 mx-auto w-96 space-y-4 overflow-hidden rounded-lg bg-white p-4 antialiased shadow-lg dark:bg-gray-800">
  <% if cart_items.present? %>
    <% cart_items.each do |item| %>
      <%= render partial: 'shared/cart_dropdown_item', locals: { book: item[:book], quantity: item[:quantity] } %>
    <% end %>
  <% end %>
  <div id="cart_dropdown_footer">
    <%= render partial: 'shared/cart_dropdown_footer' %>
  </div>
</div>

app/views/shared/_cart_dropdown_footer.html.erb
<% if @cart_items.present? %>
  <a href="<%= checkout_path %>" class="mb-2 inline-flex w-full items-center justify-center rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" role="button">
    Proceed to Checkout
  </a>
<% else %>
  <p class="text-sm font-normal text-gray-500 dark:text-gray-400">Your cart is empty</p>
<% end %>

app/views/shared/_cart_dropdown_item.html.erb
<div id="cart_dropdown_item_<%= book.id %>" class="grid grid-cols-2">
  <div>
    <a href="#" class="truncate text-sm font-semibold leading-none text-gray-900 dark:text-white hover:underline"><%= book.title %></a>
    <p class="mt-0.5 truncate text-sm font-normal text-gray-500 dark:text-gray-400"><%= number_to_currency(book.price) %></p>
  </div>
  <div class="flex items-center justify-end gap-6">
    <p class="text-sm font-normal leading-none text-gray-500 dark:text-gray-400">Qty: <%= quantity %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="relative w-full">
  <div class="absolute top-0 left-1/2 transform -translate-x-1/2 mt-4">
    <% if flash[:error] %>
      <div class="flex items-center p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800 min-w-[300px] max-w-[600px]" role="alert">
        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        <div>
          <span class="font-medium">Error:</span> <%= flash[:error] %>
        </div>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="flex items-center p-4 mb-4 text-sm text-blue-800 border border-blue-300 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400 dark:border-blue-800 min-w-[300px] max-w-[600px]" role="alert">
        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        <div>
          <span class="font-medium">Notice:</span> <%= flash[:notice] %>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="flex items-center p-4 mb-4 text-sm text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-400 dark:border-yellow-800 min-w-[300px] max-w-[600px]" role="alert">
        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        <div>
          <span class="font-medium">Alert:</span> <%= flash[:alert] %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="bg-white dark:bg-gray-800 antialiased relative">
  <div class="max-w-screen-xl px-4 mx-auto 2xl:px-0 py-4">
    <div class="flex items-center justify-between">
      <div class="flex items-center space-x-8">
        <div class="shrink-0">
          <a href="<%= root_path %>" title="BookStore" class="text-lg font-bold text-gray-900 dark:text-white">
            BookStore
          </a>
        </div>
      </div>
      <div class="flex items-center lg:space-x-2 relative">
        <button id="cart_dropdown_button" data-dropdown-toggle="cart_dropdown_button" type="button" class="inline-flex items-center rounded-lg justify-center p-2 hover:bg-gray-100 dark:hover:bg-gray-700 text-sm font-medium leading-none text-gray-900 dark:text-white">
          <span class="sr-only">Cart</span>
          <svg class="w-5 h-5 lg:me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 4h1.5L9 16m0 0h8m-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm-8.5-3h9.25L19 7H7.312"/>
          </svg>
          <span class="hidden sm:flex">My Cart</span>
          <svg class="hidden sm:flex w-4 h-4 text-gray-900 dark:text-white ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 9-7 7-7-7"/>
          </svg>
        </button>
        <%= render 'shared/cart_dropdown', cart_items: @cart_items %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "inline-flex items-center rounded-lg justify-center p-2 bg-red-600 text-white hover:bg-red-700 dark:hover:bg-red-600 text-sm font-medium leading-none" %>
      </div>
    </div>
  </div>
</nav>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dropdownButton = document.getElementById('cart_dropdown_button');
        const dropdownMenu = document.getElementById('cart_dropdown');

        dropdownButton.addEventListener('click', function () {
            dropdownMenu.classList.toggle('hidden');
        });
    });
</script>

app/views/shared/_sidebar.html.erb
<aside id="default-sidebar" class="w-64 h-screen bg-white border-r border-gray-200 dark:bg-gray-800 dark:border-gray-700" aria-label="Sidenav">
  <div class="overflow-y-auto py-5 px-3 h-full">
    <ul class="space-y-2">
      <li>
        <%= link_to "Books", admin_dashboard_books_path, data: { "turbo_frame": :"content" }, class: "flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
      </li>
      <li>
        <%= link_to "Genres", admin_dashboard_genres_path, data: { "turbo_frame": :"content" }, class: "flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
      </li>
      <li>
        <%= link_to "Orders", admin_dashboard_orders_path, data: { "turbo_frame": :"content" }, class: "flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
      </li>
      <li>
        <%= link_to "Users", admin_dashboard_users_path, data: { "turbo_frame": :"content" }, class: "flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
      </li>
    </ul>
  </div>
</aside>