config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard', to: 'dashboard#index', as: 'admin_dashboard'
  get 'admin/dashboard/books', to: 'dashboard#books'
  get 'admin/dashboard/genres', to: 'dashboard#genres'
  get 'admin/dashboard/users', to: 'dashboard#users'
  get 'admin/dashboard/orders', to: 'dashboard#orders'
  get 'home/index'

  resources :books, except: [:index]
  resources :genres, except: [:index]

  resources :genres do
    member do
      get 'delete', to: 'genres#delete'
    end
  end

  resources :books do
    member do
      get 'delete', to: 'books#delete'
    end
  end

  resources :carts, only: [] do
    post 'add', on: :collection
    delete 'remove', on: :collection
    post 'update_quantity', on: :collection
    post 'stripe_checkout', on: :collection
  end

  resources :orders, only: [] do
    collection do
      get 'success', to: 'orders#success', as: 'success'
      get 'cancel', to: 'orders#cancel', as: 'cancel'
    end
  end

  get 'checkout', to: 'carts#checkout', as: 'checkout'


  devise_for :admins, path: 'admin', skip: [:registrations, :passwords]

  devise_for :users, path: '', skip: [:passwords]

  root "home#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  validates :user_id, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart

  def checkout
    @cart_items = session[:cart] || []
    @cart_items = @cart_items.map do |book_id|
      book = Book.find(book_id)
      quantity = session[:cart_quantities] ? session[:cart_quantities][book_id.to_s] || 1 : 1
      { book: book, quantity: quantity }
    end
  end

  def stripe_checkout
    line_items = @cart_items.map do |item|
      {
        price_data: {
          currency: 'usd',
          product_data: {
            name: item[:book].title,
          },
          unit_amount: (item[:book].price * 100).to_i, # Amount in cents
        },
        quantity: item[:quantity],
      }
    end

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: line_items,
      mode: 'payment',
      success_url: success_orders_url,
      cancel_url: cancel_orders_url,
      )

    redirect_to session.url, allow_other_host: true
  end
  def add
    book = Book.find(params[:book_id])
    @cart << book.id unless @cart.include?(book.id)
    session[:cart] = @cart

    set_cart
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("cart_button_#{book.id}", partial: "home/cart_button", locals: { book: book, cart: @cart }),
          turbo_stream.prepend("cart_dropdown", partial: "shared/cart_dropdown_item", locals: { book: book, quantity: 1 }),
          turbo_stream.replace("cart_dropdown_footer", partial: "shared/cart_dropdown_footer", locals: { cart_items: @cart_items })
        ]
      end
      format.html { redirect_to root_path, notice: 'Book added to cart' }
    end
  end


  def remove
    book = Book.find(params[:book_id])
    @cart.delete(book.id)
    session[:cart_quantities].delete(book.id.to_s) if session[:cart_quantities]
    session[:cart] = @cart

    set_cart
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("cart_button_#{book.id}", partial: "home/cart_button", locals: { book: book, cart: @cart }),
          turbo_stream.remove("cart_item_#{book.id}"),
          turbo_stream.update("order_summary", partial: "carts/order_summary", locals: { cart_items: @cart_items }),
          turbo_stream.remove("cart_dropdown_item_#{book.id}"),
          turbo_stream.replace("cart_dropdown_footer", partial: "shared/cart_dropdown_footer", locals: { cart_items: @cart_items })
        ]
      end
      format.html { redirect_to root_path, notice: 'Book was successfully removed from cart.' }

    end
  end


  def update_quantity
    book = Book.find(params[:book_id])
    quantity = params[:quantity].to_i

    session[:cart_quantities] ||= {}
    session[:cart_quantities][book.id.to_s] = quantity

    set_cart
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("cart_item_#{book.id}", partial: "carts/cart_item", locals: { book: book, quantity: quantity }),
          turbo_stream.update("order_summary", partial: "carts/order_summary", locals: { cart_items: @cart_items }),
          turbo_stream.replace("cart_dropdown_item_#{book.id}", partial: "shared/cart_dropdown_item", locals: { book: book, quantity: quantity }),
          turbo_stream.replace("cart_dropdown_footer", partial: "shared/cart_dropdown_footer", locals: { cart_items: @cart_items })
        ]
      end
      format.html { redirect_to root_path, notice: 'Quantity updated successfully.' }
    end
  end


  private

  def set_cart
    session[:cart_quantities] ||= {}
    @cart = session[:cart] || []
    @cart_items = @cart.map do |book_id|
      { book: Book.find(book_id), quantity: session[:cart_quantities][book_id.to_s] || 1 }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item.html.erb
<div id="cart_item_<%= book.id %>" class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800 md:p-6">
  <div class="space-y-4 md:flex md:items-center md:justify-between md:gap-6 md:space-y-0">
    <a href="#" class="shrink-0 md:order-1">
      <% if book.image.attached? %>
        <%= image_tag url_for(book.image), class: "h-20 w-20", alt: "#{book.title} cover image" %>
      <% end %>
    </a>
    <div class="flex flex-col justify-between md:order-3 md:justify-end">
      <div class="flex items-center">
        <%= button_to update_quantity_carts_path(book_id: book.id, quantity: quantity - 1), method: :post, remote: true, class: "inline-flex items-center justify-center h-8 w-8 rounded-md border bg-gray-100 hover:bg-gray-200 mr-2", disabled: quantity <= 1 do %>
          <svg class="h-3 w-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 2">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h16"/>
          </svg>
        <% end %>
        <input type="text" class="w-12 text-center border-0 bg-transparent" value="<%= quantity %>" readonly/>
        <%= button_to update_quantity_carts_path(book_id: book.id, quantity: quantity + 1), method: :post, remote: true, class: "inline-flex items-center justify-center h-8 w-8 rounded-md border bg-gray-100 hover:bg-gray-200 ml-2" do %>
          <svg class="h-3 w-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
          </svg>
        <% end %>
      </div>
      <div class="text-end mt-2">
        <p class="text-base font-bold"><%= number_to_currency(book.price * quantity) %></p>
      </div>
    </div>
    <div class="flex items-center gap-4 md:mt-0">
      <%= button_to remove_carts_path(book_id: book.id), method: :delete, remote: true, class: "inline-flex items-center text-red-600 h-8 w-28 justify-center rounded-md border border-red-600 hover:bg-red-600 hover:text-white transition-colors" do %>
        <svg class="mr-1.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18 17.94 6M18 18 6.06 6"/>
        </svg>
        Remove
      <% end %>
    </div>
  </div>
  <div class="mt-2">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-white"><%= book.title %></h3>
  </div>
</div>

app/views/carts/_order_summary.html.erb
<div class="rounded-lg border bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800 sm:p-6">
  <p class="text-xl font-semibold text-gray-900 dark:text-white">Order summary</p>

  <div class="mt-6 space-y-4">
    <dl class="flex justify-between">
      <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Total</dt>
      <dd class="text-sm font-bold text-gray-900 dark:text-white">
        <%= number_to_currency(@cart_items.sum { |item| item[:book].price * item[:quantity] }) %>
      </dd>
    </dl>
  </div>
  <%= button_to 'Checkout with Stripe', stripe_checkout_carts_path,data: {turbo: false}, class: "mb-2 inline-flex w-full items-center justify-center rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
</div>

app/views/carts/checkout.html.erb
<section class="bg-white py-8 antialiased dark:bg-gray-900 md:py-16">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <h2 class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Shopping Cart</h2>

    <div class="mt-6 sm:mt-8 md:gap-6 lg:flex lg:items-start xl:gap-8">
      <div class="w-full lg:max-w-2xl xl:max-w-4xl">
        <div class="space-y-6">
          <% @cart_items.each do |item| %>
            <%= render partial: "carts/cart_item", locals: { book: item[:book], quantity: item[:quantity] } %>
          <% end %>
        </div>
      </div>

      <div class="flex-1 lg:mt-0">
        <div id="order_summary">
          <%= render partial: "carts/order_summary", locals: { cart_items: @cart_items } %>
        </div>
      </div>
    </div>
  </div>
</section>